title: Francesca Afruni
logo: Pictures/franci_at_KSC.jpg
description: >
  ## ğŸ“Œ Quick Navigation

- [ğŸ“ Education & Background](#education)
- [ğŸ›  Undergrad Projects](#others)
- [ğŸš Internships](#work-experience)
- [ğŸš€ Research & Programs](#workforce-developments--summer-schools)
- [ğŸ… Honors & Scholarships](#achievements--funding)

linkedin: "https://www.linkedin.com/in/francesca-afruni-147438221/"
email: "fafruni2021@my.fit.edu"
url: "https://afruni.github.io"
theme: jekyll-theme-minimal
