title: Francesca Afruni
logo: Pictures/franci_at_KSC.jpg
description: >
  ## ðŸ“Œ Quick Navigation

Welcome to my digital portfolio! My name is Francesca Afruni, Iâ€™m from Italy, and I am a dedicated aerospace engineering student at F.I.T., with a strong background in both academic research and industry internships, along with a unique history in competitive equestrian sports. Here, youâ€™ll find highlights of my projects, skills, and experiences that reflect my journey and aspirations in the aerospace field.

linkedin: "https://www.linkedin.com/in/francesca-afruni-147438221/"
email: "fafruni2021@my.fit.edu"
url: "https://afruni.github.io"
theme: jekyll-theme-minimal
